# Generated by Django 6.0.2 on 2026-02-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_alter_subscription_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="lessons_left",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
