# Generated by Django 6.0.2 on 2026-02-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_alter_subscription_lessons_left"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="end_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
