# Generated by Django 6.0.2 on 2026-02-21 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("school", "0004_alter_lesson_end_datetime"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ("start_datetime",)},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={},
        ),
        migrations.AlterField(
            model_name="lesson",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="school.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=55),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name"), name="unique_student_constraint"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacher",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name"), name="unique_teacher_constraint"
            ),
        ),
    ]
