# Generated by Django 6.0.2 on 2026-02-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_alter_lesson_options_alter_teacher_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="plan",
            new_name="subscription",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
