# Generated by Django 6.0.2 on 2026-02-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0006_rename_plan_lesson_subscription_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("name", "description"), name="unique_room_constraint"
            ),
        ),
    ]
