# Generated by Django 6.0.2 on 2026-02-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0007_room_unique_room_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Lesson is planned"),
                    ("done", "Lesson is done"),
                    ("skipped", "Lesson is skipped"),
                ],
                max_length=55,
            ),
        ),
    ]
